### ISSUE TITLE
GemEnvironmentReport started failing on CI even though it didn't fail on earlier 3.6.0 CI runs

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-common-measures-gem#145]
It also runs fine locally on my mac. Here is error on CI dashboard.

```
Failure: test_1(Minitest::Result) [:/ruby/2.7.0/json/common.rb:286]: Encoding::UndefinedConversionError: "\xE2" from ASCII-8BIT to UTF-8 :/ruby/2.7.0/json/common.rb:286:in `generate' :/ruby/2.7.0/json/common.rb:286:in `pretty_generate' /srv/jenkins/git/openstudio-common-measures-gem/PR-144/1/lib/measures/gem_env_report/resources/gem_env_info.rb:107:in `gem_env_information' /srv/jenkins/git/openstudio-common-measures-gem/PR-144/1/lib/measures/gem_env_report/measure.rb:78:in `run' /srv/jenkins/git/openstudio-common-measures-gem/PR-144/1/lib/measures/gem_env_report/tests/gem_env_report_Test.rb:72:in `test_1'
```

**Comment by DavidGoldwasser** [comment]
@mdahlhausen have you ever seen this fail before? It is fine on local run but fails on CI.

**Comment by mdahlhausen** [comment]
Never seen this before.
