### ISSUE TITLE
UnmetLoadHoursTroubleshooting measure should handle failures more gracefully

### ISSUE THREAD

**Issue by jmarrec** [NREL/openstudio-common-measures-gem#175]
User on https://unmethours.com/question/100084/cannot-run-unmet-load-hours-troubleshooting-measure/

AirLoopHVAC does not have a setpoint manager on the supply outlet node, so it crashes here:

https://github.com/NREL/openstudio-common-measures-gem/blob/6f3a8184cb0d50e3ae793be4129d895f736fd241/lib/measures/UnmetLoadHoursTroubleshooting/measure.rb#L162-L165

![Screenshot from 2024-09-23 10-57-57](https://github.com/user-attachments/assets/7a75bf45-f4e2-4f19-9dd9-8d5eb088b0eb)

**Comment by jmarrec** [comment]
After adjusting the SPMs, the measure will throw here, because the name has comas and the SQL query fails.

https://github.com/NREL/openstudio-common-measures-gem/blob/6f3a8184cb0d50e3ae793be4129d895f736fd241/lib/measures/UnmetLoadHoursTroubleshooting/measure.rb#L590-L591

```
No data found for 'Zone Mean Air Temperature' 'THERMAL ZONE: 2FL_OFFICE203,204,205' 
SWIG director method error. NoMethodError: undefined method map!' for nil:NilClass
Traceback (most recent call last): /tmp/osmodel-c616-91e0-d2d2-bb62-1727164398-0/resources/measures/UnmetLoadHoursTroubleshooting/measure.rb:591:ininitZoneMetric
```

----

Then if I fix this, it fails on

```
Making time series for envPeriod = 'RUN PERIOD 1', reportingFrequency = 'Hourly', timeSeriesName = 'Zone People Occupant Count', keyValue = 'THERMAL ZONE: ELEVATOR2'
Tuple: RUN PERIOD 1, Hourly, Zone People Occupant Count, THERMAL ZONE: ELEVATOR2 not found in data dictionary.
No time series found
No data found for 'Zone People Occupant Count' 'THERMAL ZONE: ELEVATOR2'
SWIG director method error. NoMethodError: undefined method `getDesignLoopExitTemperature' for #<OpenStudio::Model::SizingPlant:0x00007f11f2028040 @__swigtype__="_p_openstudio__model__SizingPlant">
Traceback (most recent call last):
/tmp/osmodel-c616-91e0-d2d2-bb62-1727164398-0/resources/measures/UnmetLoadHoursTroubleshooting/measure.rb:261:in `block in plant_loop_temp_vs_setpoints'
/tmp/osmodel-c616-91e0-d2d2-bb62-1727164398-0/resources/measures/UnmetLoadHoursTroubleshooting/measure.rb:244:in `each'
/tmp/osmodel-c616-91e0-d2d2-bb62-1727164398-0/resources/measures/UnmetLoadHoursTroubleshooting/measure.rb:244:in `plant_loop_temp_vs_setpoints'
/tmp/osmodel-c616-91e0-d2d2-bb62-1727164398-0/resources/measures/UnmetLoadHoursTroubleshooting/measure.rb:528:in `run'
Found error in state 'ReportingMeasures' with message: 'Runner error: Measure '/tmp/osmodel-c616-91e0-d2d2-bb62-1727164398-0/resources/measures/UnmetLoadHoursTroubleshooting/measure.rb' reported an error with [SWIG director method error. NoMethodError: undefined method `getDesignLoopExitTemperature' for #<OpenStudio::Model::SizingPlant:0x00007f11f2028040 @__swigtype__="_p_openstudio__model__SizingPlant">
Traceback (most recent call last):
/tmp/osmodel-c616-91e0-d2d2-bb62-1727164398-0/resources/measures/UnmetLoadHoursTroubleshooting/measure.rb:261:in `block in plant_loop_temp_vs_setpoints'
/tmp/osmodel-c616-91e0-d2d2-bb62-1727164398-0/resources/measures/UnmetLoadHoursTroubleshooting/measure.rb:244:in `each'
/tmp/osmodel-c616-91e0-d2d2-bb62-1727164398-0/resources/measures/UnmetLoadHoursTroubleshooting/measure.rb:244:in `plant_loop_temp_vs_setpoints'
/tmp/osmodel-c616-91e0-d2d2-bb62-1727164398-0/resources/measures/UnmetLoadHoursTroubleshooting/measure.rb:528:in `run']'
```

The proper SizingPlant getter is `double designLoopExitTemperature() const`. https://github.com/NREL/OpenStudio/blob/ba1b94b6542c1f1d4cdcdb775886852b9a82bc4f/src/model/SizingPlant.hpp#L53

I'm not sure when the Quantity getDesignLoopExitTemperature() was removed in 3.0.0

https://github.com/NREL/OpenStudio/blob/58ed43d0b1d36eec28d167b1a82a4af9e0446c2a/openstudiocore/src/model/SizingPlant.hpp#L80
