### ISSUE TITLE
view_model and view_data failing for Windows user: failed with "\xC3" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-common-measures-gem#27]
[18:12:57.715833 ERROR] :/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb failed with message Runner error :/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb failed with "\xC3" from ASCII-8BIT to UTF-8, :/ruby/2.5.0/json/common.rb:224:in `encode'
:/ruby/2.5.0/json/common.rb:224:in `generate'

Using OpenStudio Application 1.0 and latest version of this measure on BCL, updated for OpenStudio 3.0

**Comment by DavidGoldwasser** [comment]
I was able to reproduce this with view_data but not with view_mac on my mac using OpenStudio Application 1.0

`"\"\\xC3\" from ASCII-8BIT to UTF-8\n\t:/ruby/2.5.0/json/common.rb:224:in `encode'\n\t:/ruby/2.5.0/json/common.rb:224:in `generate'\n\t:/ruby/2.5.0/json/common.rb:224:in `generate'\n\t/private/var/folders/83/rcnbz4dd5qqgf7rpc69354_x0g1kng/T/osmodel-1595454666-1/resources/measures/ViewData/measure.rb:401:in `block in run'\n\teval:400:in `open'\n\t/private/var/folders/83/rcnbz4dd5qqgf7rpc69354_x0g1kng/T/osmodel-1595454666-1/resources/measures/ViewData/measure.rb:400:in `run'\n\t:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:514:in `apply_measure'\n\t:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:109:in `block in apply_measures'\n\t:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:67:in `each_index'\n\t:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/util/measure.rb:67:in `apply_measures'\n\t:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/jobs/run_reporting_measures.rb:105:in `perform'\n\t:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/run.rb:292:in `step'\n\t:/ruby/2.5.0/gems/openstudio-workflow-2.0.0/lib/openstudio/workflow/run.rb:234:in `run'\n\t:/openstudio_cli.rb:973:in `execute'\n\t:/openstudio_cli.rb:763:in `execute'\n\t:/openstudio_cli.rb:1757:in `<main>'\n\teval:149:in `eval'\n\teval:149:in `require_embedded_absolute'\n\teval:123:in `block in require'\n\teval:117:in `each'\n\teval:117:in `require'\n\teval:3:in `<main>'"`
